<?php config(require ETC_PATH . "config.php");
function p($arr){ echo'<pre>',\print_r($arr, true),'</pre>';}
function toDate($time= null,$format='Y-m-d H:i:s'){ is_null($time)&&$time= time(); return date($format,$time);}
function error($msg){ if(config('APP_DEBUG')!== true){$msg='<div style="width:500px;height:100px;border:solid 1px#333;background:#f2f2f2;padding:10px;position:absolute;top:20%;"><h1>出错啦:(</h1></div>'; exit($msg);}$e= array('title'=>'','info'=>''); if(is_string($msg)){$e['message']=$msg;$e['info']='<ol class="linenums">'; foreach(debug_backtrace() as$value){$e['info'].='<li><span>'; isset($value['file'])&&$e['info'].=$value['file'];$e['info'].='&nbsp;<strong>'; isset($value['class'])&&$e['info'].=$value['class']; isset($value['type'])&&$e['info'].=$value['type']; isset($value['function'])&&$e['info'].=$value['function'].'()</strong>';$e['info'].='</span></li>';}$e['info'].='</ol>';} else{$e=$msg;} include config('ERROR_TPL'); exit;}
function notice($args){$content=$args[1];$file=$args[2];$line=$args[3];$time= run_time('start','notice_end');$memory= number_format(memory_get_usage()/ 1024).' KB';$str='<h1 style="font-size:14px;color:#000;background:#ccc;padding:5px;width:888px;">NOTICE:'.$content.'</h1><div style="padding:5px;background:#f2f2f2;color:#000;width:888px;"><p>FILE:'.$file.'</p><p>LINE:'.$line.'</p><p>TIME:'.$time.'</p><p>MEMORY:'.$memory.'</p></div>'; echo$str;}
function load_file($file=''){ static$_files= array(); if($file!==''){ if(file_exists($file)){ if(!isset($_files[$file])){ require$file;$_files[$file]=$file;} debug::msg('加载文件'. realpath($_files[$file]).'成功');} else{ error('文件'.$file.'不存在');}} else{ return count($_files);}}
function config($key= null,$value= null){ static$_config= array(); if(is_null($key)){ return$_config;} if(is_array($key)){$_config= array_merge($_config, array_change_key_case($key)); return true;}$key= strtolower($key); if(strstr($key,'.')!== false){$key= explode('.',$key); if(!isset($_config[$key[0]][$key[1]])){ return false;} if(is_null($value)){ return$_config[$key[0]][$key[1]];} else{$_config[$key[0]][$key[1]]=$value; return true;}} if(!isset($_config[$key])){ return false;} if(is_string($key)){ if(is_null($value)){ return$_config[$key];} else{$_config[$key]=$value; return true;}} return false;}
function get_instance($class='',$method='',$args= array()){ static$_cacheObj= array(); if($class===''){ return null;} if(isset($_cacheObj[$class])){ return$_cacheObj[$class];} if($method===''){ return$_cacheObj[$class]= new$class;} if(!method_exists($class,$method)){ error('Class'.$class.'没有'.$method.'这个方法');} if(empty($args)){ return call_user_func(array(new$class,$method));} return call_user_func_array(array(new$class,$method), array($args));}
function controller($name,$method= null){ if(!is_dir(MODULE_PATH)){ error('模块'. MODULE_NAME.'不存在');} if(!file_exists(CONTROLLER_PATH.$name.'Controller.class.php')){ error('控制器'.$name.'不存在');} static$_controller= array();$path= CONTROLLER_PATH.$name.'Controller.class.php'; load_file($path);$name.='Controller'; if(!isset($_controller[$name])){$_controller[$name]= new$name;} if(is_null($method)||$method===''){ return$_controller[$name];} if(!method_exists($_controller[$name],$method)){ error('方法'.$method.'不存在');} return$_controller[$name]->$method();}
function getModuleName(){ if(isset($_GET[config('VAR_MODULE')])&&$_GET[config('VAR_MODULE')]!==''){ return$_GET[config('VAR_MODULE')];} return config('DEFAULT_MODULE');}
function getControllerName(){ if(isset($_GET[config('VAR_CONTROLLER')])&&$_GET[config('VAR_CONTROLLER')]!==''){ return$_GET[config('VAR_CONTROLLER')];} return config('DEFAULT_CONTROLLER');}
function getActionName(){ if(isset($_GET[config('VAR_ACTION')])&&$_GET[config('VAR_ACTION')]!==''){ return$_GET[config('VAR_ACTION')];} return config('DEFAULT_ACTION');}
function get_client_ip($type= 0,$advance= false){ static$ip= array(); if(isset($ip[$type])){ return$ip[$type];} if($advance=== true){ if(isset($_SERVER['HTTP_X_FORWARDED_FOR'])){$data= explode(',', filter_input(INPUT_SERVER,'HTTP_X_FORWARDED_FOR'));$pos= array_search('unknown',$data); if(false!==$pos){ unset($data[$pos]);}$ip_addr= trim($data[0]);} else if(isset($_SERVER['HTTP_CLIENT_IP'])){$ip_addr=\filter_input(INPUT_SERVER,'HTTP_CLIENT_IP');} else if(isset($_SERVER['REMOTE_ADDR'])){$ip_addr=\filter_input(INPUT_SERVER,'REMOTE_ADDR');}} else{$ip_addr=\filter_input(INPUT_SERVER,'REMOTE_ADDR')?:'0.0.0.0';}$ip[0]=$ip_addr;$ipv4=($ip_addr==='0.0.0.0')? 0: sprintf("%u", ip2long($ip_addr));$ip[1]=$ipv4; return$ip[$type];}

class Debug{ static$debug= array(); public static function msg($info){ self::$debug[]=$info;} public static function show(){$style='<style type="text/css">';$style.='.close{font-size:20px;line-height:30px;padding-right:5px;float:right;cursor:pointer}.close:hover{color:red}';$style.='</style>';$javascript='<script type="text/javascript" language="javascript">';$javascript.='var trace= document.getElementById("trace"), close= document.getElementsByClassName("close")[0];tips= document.getElementById("tips");';$javascript.='close.onclick= function(){trace.style.display="none";tips.style.display="block";document.cookie="happy_show_page_trace=no";};';$javascript.='tips.onclick= function(){trace.style.display="block";this.style.display="none";document.cookie="happy_show_page_trace=yes";};';$javascript.='if(document.cookie==="happy_show_page_trace=yes"){trace.style.display="block";tips.style.display="none";}';$javascript.='</script>';$tpl='<div id="trace" style="width:99%;height:200px;position:absolute;bottom:0;display:none">';$tpl.='<div title="关闭" style="height:30px;background:#ccc;"><div class="close">X</div></div>';$tpl.='<div style="height:150px;padding:10px;overflow:auto">'; foreach(self::$debug as$info){$tpl.=$info.'<br/>';}$tpl.='<p>页面运行时间'. run_time('start','end').'</p>';$tpl.='<p>页面内存峰值'. run_memory('start','end').'</p>';$tpl.='<p>总共加载文件数<strong>'. load_file().'</strong>个</p>';$tpl.='</div></div>';$tips='<div id="tips" style="width:80px;height:40px;background:#000;color:#fff;line-height:40px;position:absolute;bottom:0;right:0;text-align:center;cursor:pointer">'. run_time('start','end').'</div>'; echo$style.$tpl.$tips.$javascript;}}
 ?>